dist: xenial
language: python
os: linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin python-gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
pip install GDALinstall:
  - pip install GDAL=`gdal-config --version`
  - pip install -r requirements.txt
script:
  - py.test tests/ --pep8 lmpy -v --cov lmpy --cov-report term-missing
after_success:
  - coveralls
